# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from langfuse_python_sdk import Langfuse

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        langfuse = Langfuse(
        
            username = 'YOUR_USERNAME',
            password = 'YOUR_PASSWORD'
        )
        self.assertIsNotNone(langfuse)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
