# coding: utf-8
"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from langfuse_python_sdk.client_custom import ClientCustom
from langfuse_python_sdk.configuration import Configuration
from langfuse_python_sdk.api_client import ApiClient
from langfuse_python_sdk.type_util import copy_signature
from langfuse_python_sdk.apis.tags.dataset_items_api import DatasetItemsApi
from langfuse_python_sdk.apis.tags.dataset_run_items_api import DatasetRunItemsApi
from langfuse_python_sdk.apis.tags.datasets_api import DatasetsApi
from langfuse_python_sdk.apis.tags.health_api import HealthApi
from langfuse_python_sdk.apis.tags.ingestion_api import IngestionApi
from langfuse_python_sdk.apis.tags.metrics_api import MetricsApi
from langfuse_python_sdk.apis.tags.observations_api import ObservationsApi
from langfuse_python_sdk.apis.tags.projects_api import ProjectsApi
from langfuse_python_sdk.apis.tags.prompts_api import PromptsApi
from langfuse_python_sdk.apis.tags.score_api import ScoreApi
from langfuse_python_sdk.apis.tags.sessions_api import SessionsApi
from langfuse_python_sdk.apis.tags.trace_api import TraceApi



class Langfuse(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.dataset_items: DatasetItemsApi = DatasetItemsApi(api_client)
        self.dataset_run_items: DatasetRunItemsApi = DatasetRunItemsApi(api_client)
        self.datasets: DatasetsApi = DatasetsApi(api_client)
        self.health: HealthApi = HealthApi(api_client)
        self.ingestion: IngestionApi = IngestionApi(api_client)
        self.metrics: MetricsApi = MetricsApi(api_client)
        self.observations: ObservationsApi = ObservationsApi(api_client)
        self.projects: ProjectsApi = ProjectsApi(api_client)
        self.prompts: PromptsApi = PromptsApi(api_client)
        self.score: ScoreApi = ScoreApi(api_client)
        self.sessions: SessionsApi = SessionsApi(api_client)
        self.trace: TraceApi = TraceApi(api_client)
