# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCreatePromptRequest(TypedDict):
    name: str

    # Should the prompt be promoted to production immediately?
    isActive: bool

    prompt: str

class OptionalCreatePromptRequest(TypedDict, total=False):
    config: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

class CreatePromptRequest(RequiredCreatePromptRequest, OptionalCreatePromptRequest):
    pass
