# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from langfuse_python_sdk.type.ingestion_error import IngestionError
from langfuse_python_sdk.type.ingestion_success import IngestionSuccess

class RequiredIngestionResponse(TypedDict):
    successes: typing.List[IngestionSuccess]

    errors: typing.List[IngestionError]

class OptionalIngestionResponse(TypedDict, total=False):
    pass

class IngestionResponse(RequiredIngestionResponse, OptionalIngestionResponse):
    pass
