# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from langfuse_python_sdk.type.observation_level import ObservationLevel
from langfuse_python_sdk.type.observation_model_parameters import ObservationModelParameters
from langfuse_python_sdk.type.usage import Usage

class RequiredObservation(TypedDict):
    id: str

    type: str

    startTime: datetime

    level: ObservationLevel

class OptionalObservation(TypedDict, total=False):
    version: typing.Optional[str]

    traceId: typing.Optional[str]

    name: typing.Optional[str]

    endTime: typing.Optional[datetime]

    completionStartTime: typing.Optional[datetime]

    model: typing.Optional[str]

    modelParameters: typing.Optional[ObservationModelParameters]

    input: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    metadata: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    output: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    usage: Usage

    statusMessage: typing.Optional[str]

    parentObservationId: typing.Optional[str]

    promptId: typing.Optional[str]

class Observation(RequiredObservation, OptionalObservation):
    pass
