# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredOpenAIUsage(TypedDict):
    pass

class OptionalOpenAIUsage(TypedDict, total=False):
    promptTokens: typing.Optional[int]

    completionTokens: typing.Optional[int]

    totalTokens: typing.Optional[int]

class OpenAIUsage(RequiredOpenAIUsage, OptionalOpenAIUsage):
    pass
