# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from langfuse_python_sdk.type.observation_level import ObservationLevel

class RequiredOptionalObservationBody(TypedDict):
    pass

class OptionalOptionalObservationBody(TypedDict, total=False):
    version: typing.Optional[str]

    traceId: typing.Optional[str]

    name: typing.Optional[str]

    startTime: typing.Optional[datetime]

    metadata: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    input: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    output: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    level: ObservationLevel

    statusMessage: typing.Optional[str]

    parentObservationId: typing.Optional[str]

class OptionalObservationBody(RequiredOptionalObservationBody, OptionalOptionalObservationBody):
    pass
