# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from langfuse_python_sdk.type.project import Project

class RequiredProjects(TypedDict):
    data: typing.List[Project]

class OptionalProjects(TypedDict, total=False):
    pass

class Projects(RequiredProjects, OptionalProjects):
    pass
