# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredSDKLogBody(TypedDict):
    log: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

class OptionalSDKLogBody(TypedDict, total=False):
    pass

class SDKLogBody(RequiredSDKLogBody, OptionalSDKLogBody):
    pass
