# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredSession(TypedDict):
    id: str

    createdAt: datetime

    projectId: str

class OptionalSession(TypedDict, total=False):
    pass

class Session(RequiredSession, OptionalSession):
    pass
