# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from langfuse_python_sdk.type.trace import Trace
from langfuse_python_sdk.type.utils_meta_response import UtilsMetaResponse

class RequiredTraces(TypedDict):
    data: typing.List[Trace]

    meta: UtilsMetaResponse

class OptionalTraces(TypedDict, total=False):
    pass

class Traces(RequiredTraces, OptionalTraces):
    pass
