# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from langfuse_python_sdk.type.trace_body_tags import TraceBodyTags

class RequiredTraceBody(TypedDict):
    pass

class OptionalTraceBody(TypedDict, total=False):
    tags: typing.Optional[TraceBodyTags]

    version: typing.Optional[str]

    id: typing.Optional[str]

    timestamp: typing.Optional[datetime]

    name: typing.Optional[str]

    userId: typing.Optional[str]

    input: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    output: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    sessionId: typing.Optional[str]

    release: typing.Optional[str]

    metadata: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    # Make trace publicly accessible via url
    public: typing.Optional[bool]

class TraceBody(RequiredTraceBody, OptionalTraceBody):
    pass
