# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from langfuse_python_sdk.type.trace_tags import TraceTags

class RequiredTrace(TypedDict):
    # The unique identifier of a trace
    id: str

    timestamp: datetime

class OptionalTrace(TypedDict, total=False):
    tags: typing.Optional[TraceTags]

    version: typing.Optional[str]

    name: typing.Optional[str]

    input: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    output: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    sessionId: typing.Optional[str]

    release: typing.Optional[str]

    userId: typing.Optional[str]

    metadata: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    # Public traces are accessible via url without login
    public: typing.Optional[bool]

class Trace(RequiredTrace, OptionalTrace):
    pass
