# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredUsageByModel(TypedDict):
    model: str

    inputUsage: int

    outputUsage: int

    totalUsage: int

class OptionalUsageByModel(TypedDict, total=False):
    pass

class UsageByModel(RequiredUsageByModel, OptionalUsageByModel):
    pass
