# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from langfuse_python_sdk.type.model_usage_unit import ModelUsageUnit

class RequiredUsage(TypedDict):
    pass

class OptionalUsage(TypedDict, total=False):
    # Number of input units (e.g. tokens)
    input: typing.Optional[int]

    # Number of output units (e.g. tokens)
    output: typing.Optional[int]

    # Defaults to input+output if not set
    total: typing.Optional[int]

    unit: ModelUsageUnit

    # USD input cost
    inputCost: typing.Optional[typing.Union[int, float]]

    # USD output cost
    outputCost: typing.Optional[typing.Union[int, float]]

    # USD total cost, defaults to input+output
    totalCost: typing.Optional[typing.Union[int, float]]

class Usage(RequiredUsage, OptionalUsage):
    pass
