# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredUtilsMetaResponse(TypedDict):
    # current page number
    page: int

    # number of items per page
    limit: int

    # number of total items given the current filters/selection (if any)
    totalItems: int

    # number of total pages given the current limit
    totalPages: int

class OptionalUtilsMetaResponse(TypedDict, total=False):
    pass

class UtilsMetaResponse(RequiredUtilsMetaResponse, OptionalUtilsMetaResponse):
    pass
