# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

import unittest

import langfuse_python_sdk
from langfuse_python_sdk.model.model_usage_unit import ModelUsageUnit
from langfuse_python_sdk import configuration


class TestModelUsageUnit(unittest.TestCase):
    """ModelUsageUnit unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
