# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from langfuse_python_sdk.pydantic.usage_by_model import UsageByModel

class DailyMetricsDetails(BaseModel):
    date: str = Field(alias='date')

    count_traces: int = Field(alias='countTraces')

    total_cost: typing.Union[int, float] = Field(alias='totalCost')

    usage: typing.List[UsageByModel] = Field(alias='usage')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
