# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from langfuse_python_sdk.pydantic.ingestion_error import IngestionError
from langfuse_python_sdk.pydantic.ingestion_success import IngestionSuccess

class IngestionResponse(BaseModel):
    successes: typing.List[IngestionSuccess] = Field(alias='successes')

    errors: typing.List[IngestionError] = Field(alias='errors')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
