# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class OpenAIUsage(BaseModel):
    prompt_tokens: typing.Optional[typing.Optional[int]] = Field(None, alias='promptTokens')

    completion_tokens: typing.Optional[typing.Optional[int]] = Field(None, alias='completionTokens')

    total_tokens: typing.Optional[typing.Optional[int]] = Field(None, alias='totalTokens')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
