# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from langfuse_python_sdk.pydantic.trace_tags import TraceTags

class Trace(BaseModel):
    # The unique identifier of a trace
    id: str = Field(alias='id')

    timestamp: datetime = Field(alias='timestamp')

    tags: typing.Optional[TraceTags] = Field(None, alias='tags')

    version: typing.Optional[typing.Optional[str]] = Field(None, alias='version')

    name: typing.Optional[typing.Optional[str]] = Field(None, alias='name')

    input: typing.Optional[typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = Field(None, alias='input')

    output: typing.Optional[typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = Field(None, alias='output')

    session_id: typing.Optional[typing.Optional[str]] = Field(None, alias='sessionId')

    release: typing.Optional[typing.Optional[str]] = Field(None, alias='release')

    user_id: typing.Optional[typing.Optional[str]] = Field(None, alias='userId')

    metadata: typing.Optional[typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = Field(None, alias='metadata')

    # Public traces are accessible via url without login
    public: typing.Optional[typing.Optional[bool]] = Field(None, alias='public')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
