# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from langfuse_python_sdk.pydantic.model_usage_unit import ModelUsageUnit

class Usage(BaseModel):
    # Number of input units (e.g. tokens)
    input: typing.Optional[typing.Optional[int]] = Field(None, alias='input')

    # Number of output units (e.g. tokens)
    output: typing.Optional[typing.Optional[int]] = Field(None, alias='output')

    # Defaults to input+output if not set
    total: typing.Optional[typing.Optional[int]] = Field(None, alias='total')

    unit: typing.Optional[ModelUsageUnit] = Field(None, alias='unit')

    # USD input cost
    input_cost: typing.Optional[typing.Optional[typing.Union[int, float]]] = Field(None, alias='inputCost')

    # USD output cost
    output_cost: typing.Optional[typing.Optional[typing.Union[int, float]]] = Field(None, alias='outputCost')

    # USD total cost, defaults to input+output
    total_cost: typing.Optional[typing.Optional[typing.Union[int, float]]] = Field(None, alias='totalCost')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
