# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class UtilsMetaResponse(BaseModel):
    # current page number
    page: int = Field(alias='page')

    # number of items per page
    limit: int = Field(alias='limit')

    # number of total items given the current filters/selection (if any)
    total_items: int = Field(alias='totalItems')

    # number of total pages given the current limit
    total_pages: int = Field(alias='totalPages')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
