# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from langfuse_python_sdk.paths.api_public_ingestion.post import Batch
from langfuse_python_sdk.apis.tags.ingestion_api_raw import IngestionApiRaw


class IngestionApi(
    Batch,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: IngestionApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = IngestionApiRaw(api_client)
