# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from langfuse_python_sdk.paths.api_public_observations_observation_id.get import Get
from langfuse_python_sdk.paths.api_public_observations.get import GetMany
from langfuse_python_sdk.apis.tags.observations_api_raw import ObservationsApiRaw


class ObservationsApi(
    Get,
    GetMany,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ObservationsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ObservationsApiRaw(api_client)
