# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from langfuse_python_sdk.paths.api_public_prompts.post import Create
from langfuse_python_sdk.paths.api_public_prompts.get import Get
from langfuse_python_sdk.apis.tags.prompts_api_raw import PromptsApiRaw


class PromptsApi(
    Create,
    Get,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PromptsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PromptsApiRaw(api_client)
