# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from langfuse_python_sdk.paths.api_public_scores.post import CreateRaw
from langfuse_python_sdk.paths.api_public_scores_score_id.delete import DeleteRaw
from langfuse_python_sdk.paths.api_public_scores.get import GetRaw
from langfuse_python_sdk.paths.api_public_scores_score_id.get import GetByIdRaw


class ScoreApiRaw(
    CreateRaw,
    DeleteRaw,
    GetRaw,
    GetByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
