# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from langfuse_python_sdk.paths.api_public_scores.post import Create
from langfuse_python_sdk.paths.api_public_scores_score_id.delete import Delete
from langfuse_python_sdk.paths.api_public_scores.get import Get
from langfuse_python_sdk.paths.api_public_scores_score_id.get import GetById
from langfuse_python_sdk.apis.tags.score_api_raw import ScoreApiRaw


class ScoreApi(
    Create,
    Delete,
    Get,
    GetById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ScoreApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ScoreApiRaw(api_client)
