# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from langfuse_python_sdk.paths.api_public_sessions_session_id.get import Get
from langfuse_python_sdk.apis.tags.sessions_api_raw import SessionsApiRaw


class SessionsApi(
    Get,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SessionsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SessionsApiRaw(api_client)
