# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from langfuse_python_sdk import schemas  # noqa: F401


class ModelUsageUnit(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Unit of usage in Langfuse
    """
    
    @schemas.classproperty
    def CHARACTERS(cls):
        return cls("CHARACTERS")
    
    @schemas.classproperty
    def TOKENS(cls):
        return cls("TOKENS")
    
    @schemas.classproperty
    def MILLISECONDS(cls):
        return cls("MILLISECONDS")
    
    @schemas.classproperty
    def SECONDS(cls):
        return cls("SECONDS")
    
    @schemas.classproperty
    def IMAGES(cls):
        return cls("IMAGES")
