# coding: utf-8

"""
    langfuse

    ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from langfuse_python_sdk import schemas  # noqa: F401


class ObservationLevel(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    
    @schemas.classproperty
    def DEBUG(cls):
        return cls("DEBUG")
    
    @schemas.classproperty
    def DEFAULT(cls):
        return cls("DEFAULT")
    
    @schemas.classproperty
    def WARNING(cls):
        return cls("WARNING")
    
    @schemas.classproperty
    def ERROR(cls):
        return cls("ERROR")
